from __future__ import annotations

import csv
from pathlib import Path

import pandas as pd
import streamlit as st

st.set_page_config(page_title="Tipitaka Marathi Reviewer", layout="wide")
st.title("Tipitaka Marathi Reviewer")
st.caption("Truth-first review workspace for Marathi preparation")

uploaded = st.file_uploader("Open a review batch CSV", type=["csv"])

if uploaded is None:
    st.info("Upload one of the review batch CSV files generated by the pipeline.")
    st.stop()

frame = pd.read_csv(uploaded)
status_filter = st.multiselect("Filter by status", sorted(frame["status"].fillna("draft").unique()), default=sorted(frame["status"].fillna("draft").unique()))
if status_filter:
    frame = frame[frame["status"].fillna("draft").isin(status_filter)]

st.write(f"Rows: {len(frame)}")
selected_idx = st.number_input("Row index", min_value=0, max_value=max(len(frame)-1, 0), step=1)
row = frame.iloc[int(selected_idx)]

col1, col2 = st.columns(2)
with col1:
    st.subheader("Source")
    st.text_input("ID", value=str(row["id"]), disabled=True)
    st.text_input("Source path", value=str(row["source_path"]), disabled=True)
    st.text_area("Pali / source", value=str(row["pali"]), height=180, disabled=True)
    st.text_area("Draft", value=str(row.get("marathi_draft", "")), height=180, disabled=True)
with col2:
    st.subheader("Review")
    reviewed = st.text_area("Reviewed Marathi", value=str(row.get("marathi_reviewed", "")), height=180)
    status = st.selectbox("Status", ["draft", "reviewed", "vipassana_checked", "approved"], index=["draft", "reviewed", "vipassana_checked", "approved"].index(str(row.get("status", "draft"))))
    reviewer_name = st.text_input("Reviewer name", value=str(row.get("reviewer_name", "")))
    reviewer_notes = st.text_area("Reviewer notes", value=str(row.get("reviewer_notes", "")), height=120)
    vipassana_notes = st.text_area("Vipassana notes", value=str(row.get("vipassana_notes", "")), height=120)

st.warning("This app edits the current row in memory only. Export from the table below after updating fields.")
frame.loc[frame.index[int(selected_idx)], "marathi_reviewed"] = reviewed
frame.loc[frame.index[int(selected_idx)], "status"] = status
frame.loc[frame.index[int(selected_idx)], "reviewer_name"] = reviewer_name
frame.loc[frame.index[int(selected_idx)], "reviewer_notes"] = reviewer_notes
frame.loc[frame.index[int(selected_idx)], "vipassana_notes"] = vipassana_notes

st.dataframe(frame, use_container_width=True)

csv_bytes = frame.to_csv(index=False).encode("utf-8")
st.download_button("Download updated CSV", data=csv_bytes, file_name="review_batch_updated.csv", mime="text/csv")
